ldap:
  cache:
    ttl: 3600
  limit_results: 100
  connection:
    host: "localhost"
    base: o=acme
    bind_dn: uid=emmy,ou=Service_Accounts,dc=kittens,dc=net
    password: kittens
  user:
    dn_attribute: uid
    prefix: ou=People
    classes:
      - top
    filter: (|(uid=%s)(sn=%s)(cn=%s)(givenname=%s))
    attributes:
      uid: uid
      sn: sn
      givenname: givenname
      cn: cn
      uidnumber: uidnumber
  group:
    dn_attribute: cn
    member_attribute: member
    user_membership_attribute: dn
    classes:
      - groupofnames
    attributes:
      cn: name
